const Titles: { [key: string]: string } = {
    'master/company/add': 'Add Company',
    'master/company/[_id]': 'Company Details',
    'master/company/list': 'Company List',
    'master/bank/add': 'Add Bank',
    'master/bank/[_id]': 'Bank Details',
    'master/bank/list': 'Bank List',
    'master/port/add': 'Add Port',
    'master/port/[_id]': 'Port Details',
    'master/port/list': 'Port List',

    'master/PRF/add': 'Add Product Family',
    'master/PRF/[_id]': 'Product Family Details',
    'master/PRF/list': 'Product Family List',
    'master/PRS/add': 'Add Product Species',
    'master/PRS/[_id]': 'Product Species Details',
    'master/PRS/list': 'Product Species List',
    'master/PRST/add': 'Add Product Species Type',
    'master/PRST/[_id]': 'Product Species Type Details',
    'master/PRST/list': 'Product Species Type List',
    'master/PRSPW/add': 'Add Species Packing Weight',
    'master/PRSPW/[_id]': 'Product Species Packing Weight',
    'master/PRSPW/list': 'Product Species Packing Weight',

    'master/PRSPWS/add': 'Add Species Packing Weight Style',
    'master/PRSPWS/[_id]': 'Species Packing Weight Style',
    'master/PRSPWS/list': 'Species Packing Weight Style',
    'master/PRSV/add': 'Add Species Variety',
    'master/PRSV/[_id]': 'Product Species Variety',
    'master/PRSV/list': 'Product Species Variety',
    'master/PRSPS/add': 'Add Species Packing Style',
    'master/PRSPS/[_id]': 'Product Species Packing Style',
    'master/PRSPS/list': 'Product Species Packing Style',
    'master/PRSG/add': 'Add Species Grade',
    'master/PRSG/[_id]': 'Product Species Grade',
    'master/PRSG/list': 'Product Species Grade',
    'master/PRSP/add': 'Add Species Packing',
    'master/PRSP/[_id]': 'Product Species Packing',
    'master/PRSP/list': 'Product Species Packing',

    'master/test/add': 'Add Test',
    'master/test/[_id]': 'Product Test',
    'master/test/list': 'Product Test',
    // 'master/testParams/add': 'Add Test Parameters',
    // 'master/testParams/[_id]': 'Product Test Parameters',
    // 'master/testParams/list': 'Product Test Parameters',


    'product/index': 'Document',

    'product/detail/index': 'View Invoice',
    'product/detail/edit': 'Change Invoice',
    'product/item/index': 'View Products',
    'product/item/edit': 'Change Products',
    'product/item/create': 'Create Product',
    'product/codeList/index': 'View Code List',
    'product/codeList/edit': 'Change Code List',
    'product/codeList/create': 'Create Code List',
    'product/traceAbility/index': 'View Traceability',
    'product/traceAbility/edit': 'Change Traceability',
    'product/bar/index': 'View BAR',
    'product/bar/edit': 'Change BAR',
    'product/elisa/index': 'View ELISA',
    'product/elisa/edit': 'Change ELISA',
    'product/elisa/create': 'Create ELISA'
};

export default Titles